#!/bin/bash
from=/etc/*
to=emails.lst

grep -h -s -o -E "[[:alnum:]]+@[[:alpha:]]+\.[[:alpha:]]+" $from > $to

line=""
read line < $to
emails="$line"
while read line
do 
   emails="$emails, $line"
done < $to

echo $emails > $to
