#!/bin/bash
backups=$(ls "$HOME/" | grep -o -E "Backup-[0-9]{4}-[0-9]{2}-[0-9]{2}")
last_backup_path="$HOME/$(tail -1 <<< "$backups")"

if [ ! -d "$last_backup_path" ];
then
  	echo "No backups found"
  	exit 1
fi

cd "$last_backup_path"
files=$(find . -type f | grep -E -v ".[0-9]{4}-[0-9]{2}-[0-9]{2}")
restore="$HOME/restore/"

if [ ! -d "$restore" ];
then
  	mkdir "$restore"
fi

while IFS= read -r file;
do
  if [ -d "$restore/$file" ]; then
    		echo "Overwriting $file in $restore directory"
    		rm -rf "$restore/$file"
  fi
  	cp --parents "$file" "$restore/"
done <<< "$files"
