#!/bin/bash

in="iv.txt"
out="v.txt"

last_ppid=-1
children_count=0
art_sum=0

while read line; do
  ppid=$(echo "$line" | awk -F " : " '{print $2}' | grep -E -o '[0-9]+')
  art=$(echo "$line" | awk -F " : " '{print $3}' | grep -E -o '[0-9]+.?[0-9]+')
  if (( last_ppid != ppid && last_ppid != -1 )); then
    echo "Average_Running_Children_of_ParentID=$last_ppid is $(bc <<< "scale = 5; $art_sum/$children_count")"
    children_count=0
    art_sum=0
  fi
  children_count=$(($children_count+1))
  art_sum=$(bc <<< "$art_sum+$art")
  last_ppid=$ppid
done < $in > $out

echo "Average_Running_Children_of_ParentID=$last_ppid is $(bc <<< "scale = 5; $art_sum/$children_count")" >> $out
cat $out
